export const SAVED_QUICKQUESTION ='SAVED_QUICKQUESTION';
export const WORKSHEET_SAVER = 'WORKSHEET_SAVER';
export const WORKSHEET_DATA = 'WORKSHEET_DATA';
export const ADD_QUICKQUESTION = 'ADD_QUICKQUESTION';
export const ADD_WORKSHEET_DATA = 'ADD_WORKSHEET_DATA';